version: '3.5'
 
services:
  microservice-empresas:
    image: microservice-empresas
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "mongo"
    environment:
      #- "MongoDbConfiguration__ConnectionString=mongodb://mongo"
      - "MongoDbConfiguration__ConnectionString=mongodb://devs:gwEg4258npNjUGCArcTmZDF4h3HVY2es@host.docker.internal:27117/admin?ssl=false"
      - "SnsConfiguration__ArnTopico=arn:aws:sns:us-east-1:000000000000:GestaoClienteVindiTopic"
      - "AWS__Region=us-east-1"
      - "AWS_ACCESS_KEY_ID=xxx"
      - "AWS_SECRET_ACCESS_KEY=xxx"
  mongo:
    image: mongo:4.2
    volumes:
      - "./mongo-fixtures/mongoEmpresas.js:/docker-entrypoint-initdb.d/mongoEmpresas.js"
  mongo-express:
    image: mongo-express
    depends_on:
      - "mongo"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '5003:8080'
    environment:
      - SERVICES=sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "./fixtures/aws/aws.sh:/docker-entrypoint-initaws.d/aws.sh"